name: Build, Test & Package

on:
  push:
    branches:
      - main
    tags:
      - v*

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.x.x

      - name: Checkout
        uses: actions/checkout@v2

      - name: Package
        run: scripts/set-version.ps1

      - name: Build
        run: dotnet build --configuration "Release" --nologo

      - name: Test
        run: >
            dotnet test --configuration "Release" `
                --no-build `
                --no-restore `
                --nologo

      - name: Publish
        run: >
            dotnet publish --configuration "Release" `
                --no-build `
                --no-restore `
                --nologo

      - name: Package
        run: scripts/package.ps1

      - uses: actions/upload-artifact@v2
        with:
          name: app-package
          path: ${{ env.APP_PACKAGE_PATH }}
