name: Build, Test & Package

on:
  push:
    branches:
      - main
    tags:
      - v*

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.x.x

      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Git Tag
        uses: olegtarasov/get-tag@v2.1
        id: tagName

      - name: Set App Version
        run: scripts/set-version.ps1 ${{ steps.tagName.outputs.tag }}

      - name: Build App
        run: dotnet build --configuration "Release" --nologo

      - name: Test App
        run: >
            dotnet test --configuration "Release" `
                --filter "FullyQualifiedName~GoFigure.Tests" `
                --no-build `
                --no-restore `
                --nologo

      - name: Publish App
        run: >
            dotnet publish --configuration "Release" `
                --no-build `
                --no-restore `
                --nologo

      - name: Package App
        run: scripts/package.ps1 ${{ steps.tagName.outputs.tag }}

      - name: Upload App Package
        uses: actions/upload-artifact@v2
        with:
          name: app-package
          path: ${{ env.APP_PACKAGE_PATH }}
